"""create_avatars

Revision ID: b23fc8e8c62e
Revises: 894b84869139
Create Date: 2025-12-01 01:27:08.670138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23fc8e8c62e'
down_revision: Union[str, Sequence[str], None] = '894b84869139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('avatar', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('chats', 'avatar')
    # ### end Alembic commands ###
